### ISSUE TITLE
🐛 Missing lang enum constant for 'damage causes.WORLD_BORDER' / 'damage causes.KILL'

### ISSUE THREAD

**Issue by DrCausa** [SkriptLang/skript-docs#44]
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! [Skript] Severe Error:
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Something went horribly wrong with Skript.
[13:03:49 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:03:49 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:03:49 ERROR]: #!#! Here is full list of them:
[13:03:49 ERROR]: #!#! skript-reflect v2.3.1-for-skript-beta (https://github.com/TPGamesNL/skript-reflect) SkBee v2.13.0 (https://github.com/ShaneBeee/SkBee)
[13:03:49 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:03:49 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:03:49 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:03:49 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:03:49 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:03:49 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Stack trace:
[13:03:49 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "msg" is null
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.util.chat.ChatMessages.fromParsedString(ChatMessages.java:424)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:453)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:120)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
[13:03:49 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
[13:03:49 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:03:49 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:03:49 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:03:49 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:03:49 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:03:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:922)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:958)
[13:03:49 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1529)
[13:03:49 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:967)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1127)
[13:03:49 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.ah(EntityLiving.java:321)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.commands.CommandKill.a(CommandKill.java:25)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.commands.CommandKill.b(CommandKill.java:14)
[13:03:49 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[13:03:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[13:03:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2299)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2259)
[13:03:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:03:49 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:03:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:03:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:03:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[13:03:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[13:03:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:03:49 ERROR]: #!#!     at java.base/java.lang.Thread.run(Unknown Source)
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Version Information:
[13:03:49 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[13:03:49 ERROR]: #!#!     Flavor: skriptlang-github
[13:03:49 ERROR]: #!#!     Date: 03:18:03.366646700
[13:03:49 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[13:03:49 ERROR]: #!#!   Minecraft: 1.20.1
[13:03:49 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[13:03:49 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Server platform: Paper
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Current node: null
[13:03:49 ERROR]: #!#! Current item: send ">> %the damage cause%" to the attacked entity
[13:03:49 ERROR]: #!#! Current trigger: death (death) (code.sk, line 1)
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Thread: Server thread
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! Language: english
[13:03:49 ERROR]: #!#! Link parse mode: DISABLED
[13:03:49 ERROR]: #!#!
[13:03:49 ERROR]: #!#! End of Error.
[13:03:49 ERROR]: #!#!

on death:
	send ">> %damage cause%" to victim

This error occurs when I try to use "damage cause" to either send it as a message or in a condition.

These are the versions I use:
![image](https://github.com/SkriptLang/skript-docs/assets/110610073/dccd057e-ce83-4da8-a712-4c5002fbcec1)
![image](https://github.com/SkriptLang/skript-docs/assets/110610073/d2d61677-3bf7-421e-8251-553e806877be)

**Comment by AyhamAl-Ali** [comment]
Wrong place to report this issue. This is for Skript Documentation issues only.
Already a duplicate https://github.com/SkriptLang/Skript/issues/5740
